name: Cron Challenge

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install
          poetry run playwright install chromium
          sudo apt install xvfb
      - name: Run script
        run: xvfb-run poetry run python tests/test_cron_challenge.py
